"use client";
import Link from "next/link";
import { Bell, BellOff, CheckCheck, Clock3, ExternalLink, Loader2, Smartphone } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type Item={id:string;category:string;priority:string;title:string;body:string;href:string;important:boolean;readAt:string|null;createdAt:string};
type Preference={enabledCategories:string[];quietHoursEnabled:boolean;quietStart:string;quietEnd:string;detailedContentEnabled:boolean};
const categories=["ADMISSION","FOLLOW_UP","VISIT","STUDENT","FEES","DAYCARE","ATTENDANCE","WHATSAPP","CAREERS","REPORTS","SYSTEM","AI_GROWTH"];
export default function NotificationCentre(){const [items,setItems]=useState<Item[]>([]);const [preference,setPreference]=useState<Preference>({enabledCategories:categories,quietHoursEnabled:false,quietStart:"19:00",quietEnd:"08:30",detailedContentEnabled:false});const[devices,setDevices]=useState<{id:string;deviceName:string;browser:string;lastActiveAt:string}[]>([]);const[filter,setFilter]=useState("ALL");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
const load=useCallback(async()=>{setBusy(true);try{const isCategory=categories.includes(filter);const response=await fetch(`/api/admin/notifications?${isCategory?`category=${filter}`:`filter=${filter}`}`,{cache:"no-store"});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||"Could not load notifications.");setItems(data.items||[]);setDevices(data.devices||[]);setPreference(data.preference);}catch(error){setMessage(error instanceof Error?error.message:"Could not load notifications.");}finally{setBusy(false)}},[filter]);useEffect(()=>{
// Loading is the external synchronization performed by this effect.
// eslint-disable-next-line react-hooks/set-state-in-effect
void load()},[load]);
async function action(body:Record<string,unknown>){setMessage("");const response=await fetch("/api/admin/notifications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok||!data.success){setMessage(data.message||"Change could not be saved.");return;}await load()}
async function savePreferences(){await action({action:"preferences",...preference});setMessage("Notification preferences saved.")}
return <div className="space-y-6"><section className="rounded-[28px] border border-[#E5DCE9] bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black text-[#2D1736]">Alerts needing attention</h2><p className="mt-1 text-sm font-semibold text-[#796E7D]">Private details stay inside CentreOS; lock-screen alerts are brief by default.</p></div><button type="button" onClick={()=>void action({action:"mark-read"})} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[#DCCFE2] px-4 text-xs font-black text-[#632B87]"><CheckCheck size={17}/> Mark all read</button></div><div className="mt-5 flex flex-wrap gap-2">{["ALL","UNREAD","IMPORTANT","TODAY",...categories].map(value=><button key={value} onClick={()=>setFilter(value)} className={`rounded-full px-4 py-2 text-xs font-black ${filter===value?"bg-[#632B87] text-white":"bg-[#F3EDF6] text-[#632B87]"}`}>{value.replaceAll("_"," ")}</button>)}</div>{busy?<p className="mt-6 flex items-center gap-2 text-sm font-bold text-[#796E7D]"><Loader2 className="animate-spin" size={17}/> Loading alerts…</p>:items.length===0?<div className="mt-6 rounded-2xl bg-[#F7F4F8] p-6 text-center"><BellOff className="mx-auto text-[#8B7A91]"/><p className="mt-2 text-sm font-bold text-[#6A5C70]">No alerts in this view.</p></div>:<div className="mt-5 space-y-3">{items.map(item=><article key={item.id} className={`rounded-2xl border p-4 ${item.readAt?"border-[#EEE8F0] bg-white":"border-[#CDB7D8] bg-[#FCF9FD]"}`}><div className="flex items-start gap-3"><span className="mt-0.5 rounded-xl bg-[#F1E8F5] p-2 text-[#632B87]"><Bell size={17}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 text-[10px] font-black"><span className="rounded-full bg-[#EEE4F3] px-2 py-1 text-[#632B87]">{item.category.replaceAll("_"," ")}</span><span className="rounded-full bg-[#F3F1F4] px-2 py-1 text-[#6D6270]">{item.priority}</span></div><h3 className="mt-2 font-black text-[#2D1736]">{item.title}</h3><p className="mt-1 text-sm font-semibold text-[#706574]">{item.body}</p><p className="mt-2 text-xs font-semibold text-[#918596]">{new Date(item.createdAt).toLocaleString("en-IN")}</p></div><div className="flex shrink-0 flex-col gap-2"><Link onClick={()=>void action({action:"mark-read",id:item.id})} href={item.href} className="inline-flex min-h-10 items-center gap-1.5 rounded-xl bg-[#632B87] px-3 text-xs font-black text-white">Open <ExternalLink size={14}/></Link>{!item.readAt?<button onClick={()=>void action({action:"mark-read",id:item.id})} className="text-xs font-black text-[#632B87]">Mark read</button>:null}</div></div></article>)}</div>}</section>
<section className="grid gap-5 xl:grid-cols-2"><div className="rounded-[28px] border border-[#E5DCE9] bg-white p-5 sm:p-7"><h2 className="flex items-center gap-2 text-lg font-black text-[#2D1736]"><Clock3 size={19}/> Notification preferences</h2><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-3">{categories.map(category=><label key={category} className="flex items-center gap-2 rounded-xl border border-[#E8E0EB] p-3 text-xs font-bold text-[#5E5362]"><input type="checkbox" checked={preference.enabledCategories.includes(category)} onChange={(event)=>setPreference({...preference,enabledCategories:event.target.checked?[...preference.enabledCategories,category]:preference.enabledCategories.filter(item=>item!==category)})}/>{category.replaceAll("_"," ")}</label>)}</div><label className="mt-5 flex items-center gap-2 text-sm font-bold text-[#514655]"><input type="checkbox" checked={preference.quietHoursEnabled} onChange={(e)=>setPreference({...preference,quietHoursEnabled:e.target.checked})}/> Use quiet hours</label><div className="mt-3 flex gap-3"><input type="time" value={preference.quietStart} onChange={(e)=>setPreference({...preference,quietStart:e.target.value})} className="rounded-xl border border-[#DCCFE2] px-3 py-2"/><input type="time" value={preference.quietEnd} onChange={(e)=>setPreference({...preference,quietEnd:e.target.value})} className="rounded-xl border border-[#DCCFE2] px-3 py-2"/></div><button onClick={()=>void savePreferences()} className="mt-5 min-h-11 rounded-xl bg-[#632B87] px-5 text-xs font-black text-white">Save preferences</button></div><div className="rounded-[28px] border border-[#E5DCE9] bg-white p-5 sm:p-7"><h2 className="flex items-center gap-2 text-lg font-black text-[#2D1736]"><Smartphone size={19}/> Registered devices</h2>{devices.length?<div className="mt-4 space-y-3">{devices.map(device=><div key={device.id} className="rounded-xl bg-[#F7F3F8] p-4"><p className="font-black text-[#35253B]">{device.deviceName}</p><p className="mt-1 line-clamp-1 text-xs font-semibold text-[#807384]">Last active {new Date(device.lastActiveAt).toLocaleString("en-IN")}</p><button onClick={()=>void action({action:"disable-device",id:device.id})} className="mt-2 text-xs font-black text-red-700">Disable this device</button></div>)}</div>:<p className="mt-4 text-sm font-semibold text-[#796E7D]">No Chrome device has been enabled yet. Use “Enable alerts” in the top bar after production Firebase messaging is configured.</p>}</div></section>{message?<p role="status" className="rounded-xl bg-[#F4EDF7] p-3 text-sm font-bold text-[#632B87]">{message}</p>:null}</div>}
