CREATE TYPE "EnrollmentContractStatus" AS ENUM ('DRAFT', 'ACTIVE', 'PAUSED', 'ENDED', 'CANCELLED');
CREATE TYPE "ContractServiceType" AS ENUM ('PRESCHOOL', 'DAYCARE', 'MEAL', 'ANNUAL', 'KIT', 'ADMISSION', 'OTHER');
CREATE TYPE "ContractServiceFrequency" AS ENUM ('MONTHLY', 'ONE_TIME', 'CUSTOM');
CREATE TYPE "ContractServiceStatus" AS ENUM ('DRAFT', 'ACTIVE', 'ENDED', 'WAIVED', 'CANCELLED');
CREATE TYPE "FinancialCorrectionType" AS ENUM ('ADJUSTMENT', 'CREDIT_NOTE', 'REFUND', 'REVERSAL');
CREATE TYPE "FinancialCorrectionStatus" AS ENUM ('DRAFT', 'APPROVED', 'APPLIED', 'CANCELLED');

ALTER TYPE "FeeInvoiceStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
